import { GeistSans } from "geist/font/sans";
import "src/styles/globals.css";
import NavBar from "~/components/navbar";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata = {
  title: "Ben's first T3 app!",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/Subject.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <NavBar />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
